
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>欢迎您参加肖庆功&amp;柴垠洁的婚礼</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
<!--     <meta property="wb:webmaster" content="9bcc835d7e7d42ec" /> -->

    <!-- Le styles -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
    <style>

    /* GLOBAL STYLES
    -------------------------------------------------- */
    /* Padding below the footer and lighter body text */

    body {
      padding-bottom: 40px;
      color: #5a5a5a;
    }



    /* CUSTOMIZE THE CAROUSEL
    -------------------------------------------------- */

    /* Carousel base class */
    .carousel {
      margin-bottom: 60px;
    }

    .carousel .container {
      position: relative;
      z-index: 9;
    }

    .carousel-control {
      height: 80px;
      margin-top: 0;
      font-size: 100px;
      text-shadow: 0 1px 1px rgba(0,0,0,.4);
      background-color: transparent;
      border: 0;
      z-index: 10;
    }

    .carousel .item {
	  height: 500px;
    }
    .carousel img {
      position: absolute;
      top: 0;
      left: 0;
      min-width: 100%;
/*       height: 500px; */
    }

    .carousel-caption {
      background-color: transparent;
      position: static;
      max-width: 600px;
      padding: 0 30px;
      margin-top: 250px;
    }
    .carousel-caption h1,
    .carousel-caption .lead {
      margin: 0;
      line-height: 1.25;
      color: #dd1144;
      text-shadow: 0 1px 1px rgba(0,0,0,.4);
    }
    .carousel-caption .btn {
      margin-top: 10px;
    }



    /* MARKETING CONTENT
    -------------------------------------------------- */

    /* Center align the text within the three columns below the carousel */
    .marketing .span4 {
      text-align: center;
    }
    .marketing h2 {
      font-weight: normal;
    }
    .marketing .span4 p {
      margin-left: 10px;
      margin-right: 10px;
    }


    /* Featurettes
    ------------------------- */

    .featurette-divider {
      margin: 80px 0; /* Space out the Bootstrap <hr> more */
    }
    .featurette {
      padding-top: 120px; /* Vertically center images part 1: add padding above and below text. */
      overflow: hidden; /* Vertically center images part 2: clear their floats. */
    }
    .featurette-image {
      margin-top: -120px; /* Vertically center images part 3: negative margin up the image the same amount of the padding to center it. */
    }

    /* Give some space on the sides of the floated elements so text doesn't run right into it. */
    .featurette-image.pull-left {
      margin-right: 40px;
    }
    .featurette-image.pull-right {
      margin-left: 40px;
    }

    /* Thin out the marketing headings */
    .featurette-heading {
      font-size: 50px;
      font-weight: 300;
      line-height: 1;
      letter-spacing: -1px;
    }



    /* RESPONSIVE CSS
    -------------------------------------------------- */

    @media (max-width: 979px) {

      .container.navbar-wrapper {
        margin-bottom: 0;
        width: auto;
      }
      .navbar-inner {
        border-radius: 0;
        margin: -20px 0;
      }

      .carousel .item {
        height: 500px;
      }
      .carousel img {
        width: auto;
        height: 500px;
      }

      .featurette {
        height: auto;
        padding: 0;
      }
      .featurette-image.pull-left,
      .featurette-image.pull-right {
        display: block;
        float: none;
        max-width: 40%;
        margin: 0 auto 20px;
      }
    }


    @media (max-width: 767px) {

      .navbar-inner {
        margin: -20px;
      }

      .carousel {
        margin-left: -20px;
        margin-right: -20px;
      }
      .carousel .container {

      }
      .carousel .item {
          overflow: hidden;
          width: auto;
          max-height: 300px;
      }
      .carousel img {
      	width: auto;
	    max-height: 300px;
      }
      .carousel-caption {
        width: 70%;
        padding: 0 50px;
        margin-top: 150px;
      }
      .carousel-caption h1 {
        font-size: 30px;
      }
      .carousel-caption .lead,
      .carousel-caption .btn {
        font-size: 18px;
      }

      .marketing .span4 + .span4 {
        margin-top: 40px;
      }

      .featurette-heading {
        font-size: 30px;
      }
      .featurette .lead {
        font-size: 18px;
        line-height: 1.5;
      }

    }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="/javascripts/html5shiv.js"></script>
    <![endif]-->

  </head>

  <body>



    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <img src="/images/banner.png" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>我们要结婚啦！</h1>
              <a data-toggle="modal" class="btn btn-large btn-danger" href="#myModal"><i class="icon icon-white icon-heart"></i>我要出席</a>
            </div>
          </div>
        </div>
      </div>
    </div><!-- /.carousel -->

<hr>

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
      	<div class="span4">
          <img class="img-rounded" src="/images/2.png">
          <h2>肖庆功</h2>
          <p><a class="btn btn-success" href="tel:159-4068-5555">电话：159-4068-5555</a></p>
          <p><a class="btn btn-info" href="sms:159-4068-5555">短信：159-4068-5555</a></p>
        </div><!-- /.span4 -->
      
        <div class="span4">
          <img class="img-rounded" src="/images/1.png">
          <h2>柴垠洁</h2>
          <p><a class="btn btn-success" href="tel:182-4167-7789">电话: 182-4167-7789</a></p>
          <p><a class="btn btn-info" href="sms:182-4167-7789">短信: 182-4167-7789</a></p>
        </div><!-- /.span4 -->
        
        <div class="span4">
          <img class="img-rounded" src="/images/map.png">
          <h2>婚礼日程</h2>
          <p>
          <strong>时间：</strong>2015年5月23日 10点58分<br>
          <strong>地点：</strong>辽宁省锦州市长城宾馆<br>
          </p>
          <p><a target="_blank" class="btn btn-success" href="http://j.map.baidu.com/YoJw1">查看地图</a></p>
        </div><!-- /.span4 -->
      </div><!-- /.row -->

<!-- Model -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-header">
	    <button id="closePop" type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">来宾登记</h3>
	  </div>
	  <div class="modal-body">
	    <form method="post" class="form-horizontal" id="myForm">
			<fieldset>
	
			<!-- Form Name -->
	
			<!-- Text input-->
			<div class="control-group">
			  <div class="controls">
			    <input id="name" name="name" type="text" placeholder="您的大名" class="input-medium" required="required">
			
			  </div>
			</div>
	
			<!-- Text input-->
			<div class="control-group">
			  <div class="controls">
			    <input id="phone" name="phone" type="text" placeholder="手机号码" class="input-medium" required="required">
			  </div>
			</div>
	
			<!-- Text input-->
			<div class="control-group">
			  <div class="controls">
			    <input id="number_of_attendee" name="number_of_attendee" type="text" placeholder="出席人数" class="input-small" required="required">
			  </div>
			</div>
	
			<!-- Multiple Radios -->
			<div class="control-group">
			  <div class="controls">
			    <label class="radio inline" for="room_reserve-0">
			      <input type="radio" name="room_reserve" id="room_reserve-0" value="嗯哪">
			      帮我订宾馆
			    </label>
			    <label class="radio inline" for="room_reserve-1">
			      <input type="radio" name="room_reserve" id="room_reserve-1" value="不用" checked="checked">
			      不用
			    </label>
			    <br>
			    <textarea id="room_description" name="room_description">
                    到达日期:
                    到达车次:
                    同行人数:
                    是否需要准备素食:
                    祝福话语:
                </textarea>
			  </div>
			</div>
		</fieldset>
		</form>
		<div class="control-group text-center">
			  <div class="controls">
			    <button onclick="submitForm();" class="btn btn-primary btn-success">填好了~</button>
			  </div>
		</div>
	</div>
	
	

	 
</div> 
      <!-- FOOTER -->
      <footer>
        
      </footer>

    </div><!-- /.container -->



    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/javascripts/jquery-1.10.2.min.js"></script>
    <script src="/javascripts/bootstrap.min.js"></script>

    <script>
    !function ($) {
        $(function(){
          // carousel demo
          $('#myCarousel').carousel()
        });
      }(window.jQuery);
      
      function submitForm(){
          var data = {
          name: $("#name").val(),
          phone: $("#phone").val(),
          number_of_attendee: $("#number_of_attendee").val(),
          room_reserve: $('input[name=room_reserve]:checked', '#myForm').val(),
          room_description: $("#room_description").val()
          };
          $.post("", data, function(rdata){
        	  alert(rdata);
        	  if(rdata=="妥！"){
            	  $("#closePop").click();
        	  }
          });
      }

    </script>
  </body>
</html>
